//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndecommPOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int propertyid { get; set; }
        public Nullable<int> yearbuilt { get; set; }
        public Nullable<int> listprice { get; set; }
        public Nullable<int> monthlyrent { get; set; }
        public string grossyield { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string district { get; set; }
        public string state { get; set; }
        public Nullable<int> zip { get; set; }
        public Nullable<int> zipplus4 { get; set; }
    }
}
